### ISSUE TITLE
[BUG] When killing dragons they can suddenly disappear

### ISSUE THREAD

**Issue by Dragon5199** [ROMVoid95/Scepter-5-Kingdoms#1]
__**Describe the problem**__
> When killing dragons they can suddenly disappear

__**Steps To Reproduce**__
> I was simply just hitting the dragon with an enchanted fire dragon bone sword when it just suddenly siappeared when it got to low health, i was on my own when fighting it(if that is relevant)

__**Modpack Version Your On**__
> b1.10

__**Crashlog Link**__
Add link

**Comment by ROMVoid95** [comment]
@Dragon5199 do you have any client side mods that are not included in the modpack?

**Comment by ROMVoid95** [comment]
add

**Comment by ROMVoid95** [comment]
Problem appears to be fixed on mod update
