### ISSUE TITLE
[BUG] Rustic Chair Auto Disconnect 

### ISSUE THREAD

**Issue by greenalex27** [ROMVoid95/Scepter-5-Kingdoms#2]
When you sit in a Rustic chair, it will disconnect you with the error: A fatal error has occurred this connection is terminated.

**Comment by ROMVoid95** [comment]
Can you provide the logs from your end?

**Comment by greenalex27** [comment]
Sorry pastebin was being really laggy, here is a dropbox of the debug file. https://www.dropbox.com/s/2rwukeynldw9mar/debug.log?dl=0

**Comment by ROMVoid95** [comment]
Okay. You can use https://haste.in in the future
