### ISSUE TITLE
[BUG] Raw Longbow Dupe

### ISSUE THREAD

**Issue by greenalex27** [ROMVoid95/Scepter-5-Kingdoms#3]
__**Describe the problem**_
Raw Longbow dupe that infinitely made raw longbows
__**Steps To Reproduce**__
1. Get someone to place two yew staves on each other, in the way that you make a longbow, in a claim you don't have perms in.
2. once it is placed get a work blade and right-click the bottom one as to make the raw longbow.
3. The stave will stay while the raw longbow is still created. 

__**Modpack Version Your On**__
b1.2.0

**Comment by ROMVoid95** [comment]
This can be fixed with changes to EagleFactions configs server-side. Will apply the needed changes
