### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by GalliumArmor** [ROMVoid95/Scepter-5-Kingdoms#6]
__**Describe the problem**__
>While attempting to download the technic launcher version, this message appears
![image](https://user-images.githubusercontent.com/38893702/91650419-653b7c00-ea4d-11ea-8f42-705897fd35ad.png)

__**Steps To Reproduce**__
> pressing the install button on the technic launcher version

__**Modpack Version Your On**__
> attempting to download b1.4.1 version

__**Crashlog Link**__

**Comment by ROMVoid95** [comment]
Can you try the download again please?

**Comment by GalliumArmor** [comment]
It downloaded successfully and I was able to launch the game.
